name: pyCovariance-package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        $CONDA/bin/conda install -y --file requirements.txt
    - name: Install pymanopt and pyCovariance
      run: |
        cd submodules/pymanopt_fork
        python setup.py install
        cd ../pyCovariance
        python setup.py install
    - name: Insall robuststats
      run: python setup.py install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 robuststats tests examples --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 robuststats tests examples --count --exit-zero --statistics
    - name: Test with nose2
      run: |
        nose2 -v --with-coverage && coverage combine
